const express = require('express');
const http = require('http');
const WebSocket = require('ws');
const { WebcastPushConnection } = require('tiktok-live-connector');
const path = require('path');
const gTTS = require('google-tts-api');
const https = require('https');
const fs = require('fs');
const multer = require('multer');
const crypto = require('crypto');
const { MsEdgeTTS, OUTPUT_FORMAT } = require('msedge-tts');

const IS_PKG = typeof process.pkg !== 'undefined';
const REAL_BASE = IS_PKG
  ? path.dirname(process.execPath)
  : process.env.TIKTOK_RESOURCES_PATH || __dirname;

const app = express();
const server = http.createServer(app);
const wss = new WebSocket.Server({ server });

// Uploads directory for custom overlay backgrounds
const UPLOADS_DIR = path.join(REAL_BASE, 'public', 'uploads');
if (!fs.existsSync(UPLOADS_DIR)) {
  fs.mkdirSync(UPLOADS_DIR, { recursive: true });
}

const uploadStorage = multer.diskStorage({
  destination: (_req, _file, cb) => cb(null, UPLOADS_DIR),
  filename: (_req, file, cb) => {
    const ext = path.extname(file.originalname).toLowerCase() || '.png';
    const name = `bg_${Date.now()}_${Math.random().toString(36).slice(2, 8)}${ext}`;
    cb(null, name);
  }
});

const upload = multer({
  storage: uploadStorage,
  limits: { fileSize: 8 * 1024 * 1024 }, // 8 MB max
  fileFilter: (_req, file, cb) => {
    const allowedMime = ['image/png', 'image/jpeg', 'image/jpg', 'image/webp', 'image/gif'];
    const allowedExt = ['.png', '.jpg', '.jpeg', '.webp', '.gif'];
    const ext = path.extname(file.originalname).toLowerCase();
    if (allowedMime.includes(file.mimetype) || allowedExt.includes(ext)) cb(null, true);
    else cb(new Error('Solo se permiten imágenes PNG, JPG, WebP o GIF'));
  }
});

app.use(express.static(path.join(REAL_BASE, 'public')));
app.use('/gifts', express.static(path.join(REAL_BASE, 'gifts')));
app.use('/uploads', express.static(UPLOADS_DIR));
app.use(express.json());

let tiktokConnection = null;
let currentUsername = null;
let reconnectAttempts = 0;
let reconnectTimer = null;
let isConnecting = false;
const MAX_RECONNECT_ATTEMPTS = 5;

const clients = new Set();
const likePendingTimers = new Map();
const config = {
  LIKE_DEBOUNCE_MS: 1500,
  TTS_MAX_CHARS: 500,
  rateLimitEnabled: false,
  TTS_RATE_LIMIT_MAX: 10,
  TTS_RATE_WINDOW_MS: 5000,
  MAX_QUEUE_MSG: 15,
  giftConversionRates: { tiktokUsdPerCoin: 0.0105 },
};

const overlayState = {
  followCount: 0,
  baseFollowerCount: 0,
  topLikers: new Map(),
  sharers: [],
  credits: {
    donors: [],
    followers: [],
    sharers: [],
  },
};
let followerRefreshTimer = null;
function resetOverlayState() {
  overlayState.followCount = 0;
  overlayState.topLikers.clear();
  overlayState.baseFollowerCount = 0;
  overlayState.sharers = [];
  overlayState.credits.donors = [];
  overlayState.credits.followers = [];
  overlayState.credits.sharers = [];
}

function log(level, ctx, msg, data = null) {
  const fn = level === 'error' ? console.error : console.log;
  fn(JSON.stringify({ ts: new Date().toISOString(), level, ctx, msg, ...(data && { data }) }));
}

function extractFollowerCount(roomInfo) {
  try {
    const owner = roomInfo && roomInfo.owner;
    const fi = owner && (owner.follow_info || owner.followInfo);
    const count = fi && (fi.follower_count || fi.followerCount || fi.fan_count || fi.fanCount);
    if (typeof count === 'number' && count > 0) return count;
  } catch (e) {}
  return 0;
}

function startFollowerRefresh() {
  stopFollowerRefresh();
  followerRefreshTimer = setInterval(async () => {
    if (!tiktokConnection || !currentUsername) return;
    try {
      const roomInfo = await tiktokConnection.getRoomInfo();
      const newCount = extractFollowerCount(roomInfo);
      if (newCount > 0 && newCount !== overlayState.baseFollowerCount) {
        overlayState.baseFollowerCount = newCount;
        broadcast({ type: 'follower-base', count: newCount });
        log('info', 'followers', 'Base follower count refreshed', { count: newCount });
      }
    } catch (err) {
      log('warn', 'followers', 'Failed to refresh follower count', { error: err.message });
    }
  }, 5 * 60 * 1000);
}

function stopFollowerRefresh() {
  if (followerRefreshTimer) {
    clearInterval(followerRefreshTimer);
    followerRefreshTimer = null;
  }
}

function sanitizeForTTS(text) {
  return text
    .replace(/https?:\/\/\S+/g, 'link')
    .replace(/@\w+/g, '')
    .replace(/(.)\1{4,}/g, '$1$1$1')
    .replace(/[^\p{L}\p{N}\p{Z}\p{P}]/gu, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function cleanName(str = '') {
  return str
    .replace(/^@/, '')
    .replace(/[_.\-]+/g, ' ')
    .replace(/[^\p{L}\p{N} ]/gu, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function isAutoGenerated(name) {
  return /^user\d{4,}$/i.test(name) || /^\d{4,}$/.test(name);
}

function isUnreadable(name) {
  return !/[\p{L}\p{N}]/u.test(name);
}

function resolveDisplayName(nickname, uniqueId) {
  const nick = cleanName(nickname || '');
  if (nick && !isUnreadable(nick) && !isAutoGenerated(nick)) return nick;
  const uid = cleanName(uniqueId || '');
  if (uid && !isUnreadable(uid) && !isAutoGenerated(uid)) return uid;
  return 'USER';
}

const BLOCKED_WORDS_FILE = path.join(REAL_BASE, 'blocked-words.md');
const blockedWords = new Set();

function loadBlockedWordsFromFile() {
  try {
    if (!fs.existsSync(BLOCKED_WORDS_FILE)) return;
    const content = fs.readFileSync(BLOCKED_WORDS_FILE, 'utf-8');
    const lines = content.split(/\r?\n/);
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
        const word = trimmed.slice(2).toLowerCase().trim();
        if (word) blockedWords.add(word);
      }
    }
    log('info', 'blocked-words', 'loaded from file', { count: blockedWords.size });
  } catch (err) {
    log('error', 'blocked-words', 'failed to load file', { error: err.message });
  }
}

function saveBlockedWordsToFile() {
  try {
    const sorted = [...blockedWords].sort((a, b) => a.localeCompare(b));
    const lines = [
      '# Palabras Prohibidas — TikTok Live TTS',
      '',
      'Edita este archivo directamente o usa la web en `/advanced.html`.',
      'Las palabras se comparan en minúsculas, sin importar acentos.',
      ''
    ];
    for (const word of sorted) {
      lines.push(`- ${word}`);
    }
    lines.push('');
    fs.writeFileSync(BLOCKED_WORDS_FILE, lines.join('\n'), 'utf-8');
    log('info', 'blocked-words', 'saved to file', { count: sorted.length });
  } catch (err) {
    log('error', 'blocked-words', 'failed to save file', { error: err.message });
  }
}

function isSpam(comment) {
  if (comment.length > 300) return true;
  if (/^(.)\1+$/.test(comment.trim())) return true;
  const lower = comment.toLowerCase();
  for (const w of blockedWords) if (lower.includes(w)) return true;
  return false;
}

const ttsRequestTimes = [];

function isTTSRateLimited() {
  if (!config.rateLimitEnabled) return false;
  const now = Date.now();
  while (ttsRequestTimes.length && ttsRequestTimes[0] < now - config.TTS_RATE_WINDOW_MS)
    ttsRequestTimes.shift();
  if (ttsRequestTimes.length >= config.TTS_RATE_LIMIT_MAX) return true;
  ttsRequestTimes.push(now);
  return false;
}

// Broadcast to all connected browser clients
function broadcast(data) {
  const msg = JSON.stringify(data);
  clients.forEach(client => {
    if (client.readyState === WebSocket.OPEN) {
      client.send(msg);
    }
  });
}

// Setup TikTok connection handlers (reusable for reconnect)
function setupTikTokConnection(cleanUsername) {
  if (tiktokConnection) {
    tiktokConnection.removeAllListeners();
  }
  tiktokConnection = new WebcastPushConnection(cleanUsername, {
    processInitialData: false,
    enableExtendedGiftInfo: false,
    enableWebsocketUpgrade: true,
    requestPollingIntervalMs: 2000,
  });

  tiktokConnection.on('chat', (data) => {
    log('debug', 'chat', 'raw', { preview: JSON.stringify(data).substring(0, 100) });
    if (!data.comment || !data.comment.trim()) return;
    if (isSpam(data.comment.trim())) return;
    broadcast({
      type: 'chat',
      platform: 'tiktok',
      user: resolveDisplayName(data.nickname, data.uniqueId),
      comment: sanitizeForTTS(data.comment.trim()),
      timestamp: Date.now()
    });
  });

  tiktokConnection.on('gift', (data) => {
    if (data.giftType === 1 && !data.repeatEnd) return;
    const user = resolveDisplayName(data.nickname, data.uniqueId);
    const repeatCount = data.repeatCount || 1;
    const coins = (data.diamondCount || 0) * repeatCount;
    const usdRaw = coins * config.giftConversionRates.tiktokUsdPerCoin;
    const usdValue = usdRaw > 0 ? usdRaw.toFixed(2) : null;
    overlayState.credits.donors.push({ user, giftName: data.giftName, count: repeatCount, ts: Date.now() });
    broadcast({
      type: 'gift',
      user,
      giftName: data.giftName,
      giftId: data.giftId,
      giftPictureUrl: data.giftPictureUrl || null,
      repeatCount,
      usdValue,
      timestamp: Date.now()
    });
  });

  tiktokConnection.on('like', (data) => {
    const userId = resolveDisplayName(data.nickname, data.uniqueId);

    if (likePendingTimers.has(userId)) {
      clearTimeout(likePendingTimers.get(userId).timer);
    } else {
      likePendingTimers.set(userId, { timer: null, count: 0 });
    }

    const pending = likePendingTimers.get(userId);
    pending.count += (data.likeCount || 1);
    pending.timer = setTimeout(() => {
      likePendingTimers.delete(userId);
      broadcast({
        type: 'like',
        user: userId,
        likeCount: pending.count,
        timestamp: Date.now()
      });
      const existing = overlayState.topLikers.get(userId) || { user: userId, totalLikes: 0 };
      existing.totalLikes += pending.count;
      overlayState.topLikers.set(userId, existing);
    }, config.LIKE_DEBOUNCE_MS);
  });

  tiktokConnection.on('member', (data) => {
    broadcast({
      type: 'join',
      user: resolveDisplayName(data.nickname, data.uniqueId),
      timestamp: Date.now()
    });
  });

  tiktokConnection.on('follow', (data) => {
    const user = resolveDisplayName(data.nickname, data.uniqueId);
    overlayState.credits.followers.push({ user, ts: Date.now() });
    broadcast({
      type: 'follow',
      user,
      timestamp: Date.now()
    });
    overlayState.followCount += 1;
  });

  tiktokConnection.on('share', (data) => {
    const user = resolveDisplayName(data.nickname, data.uniqueId);
    overlayState.sharers.push({ user, ts: Date.now() });
    overlayState.credits.sharers.push({ user, ts: Date.now() });
    broadcast({ type: 'share', user, timestamp: Date.now() });
  });

  tiktokConnection.on('disconnected', () => {
    broadcast({ type: 'disconnected' });
    if (reconnectAttempts < MAX_RECONNECT_ATTEMPTS && currentUsername) {
      const delay = Math.min(1000 * Math.pow(2, reconnectAttempts), 30000);
      reconnectAttempts++;
      log('warn', 'reconnect', `Intento ${reconnectAttempts} en ${delay}ms`, { username: currentUsername });
      broadcast({ type: 'reconnecting', attempt: reconnectAttempts, delayMs: delay });
      reconnectTimer = setTimeout(() => attemptReconnect(currentUsername), delay);
    }
  });

  tiktokConnection.on('error', (err) => {
    broadcast({ type: 'error', message: err.message || 'Error de conexión' });
  });
}

async function attemptReconnect(username) {
  try {
    if (tiktokConnection) {
      try { tiktokConnection.disconnect(); } catch (e) {}
      tiktokConnection = null;
    }

    resetOverlayState();
    setupTikTokConnection(username);
    const state = await tiktokConnection.connect();

    const baseCount = extractFollowerCount(state && state.roomInfo);
    if (baseCount > 0) {
      overlayState.baseFollowerCount = baseCount;
      broadcast({ type: 'follower-base', count: baseCount });
    }
    startFollowerRefresh();

    currentUsername = username;
    reconnectAttempts = 0;
    if (reconnectTimer) { clearTimeout(reconnectTimer); reconnectTimer = null; }

    broadcast({ type: 'connected', username });
    log('info', 'reconnect', 'Reconexion exitosa', { username });
  } catch (err) {
    log('error', 'reconnect', 'Fallo reconexion', { attempt: reconnectAttempts, error: err.message });
    if (reconnectAttempts < MAX_RECONNECT_ATTEMPTS && currentUsername) {
      const delay = Math.min(1000 * Math.pow(2, reconnectAttempts), 30000);
      reconnectAttempts++;
      broadcast({ type: 'reconnecting', attempt: reconnectAttempts, delayMs: delay });
      reconnectTimer = setTimeout(() => attemptReconnect(username), delay);
    }
  }
}

// WebSocket connections from browser
wss.on('connection', (ws) => {
  clients.add(ws);
  log('info', 'ws', 'Browser client connected', { total: clients.size });

  ws.on('close', () => {
    clients.delete(ws);
    log('info', 'ws', 'Browser client disconnected', { total: clients.size });
  });
});

// Connect to TikTok Live
app.post('/api/connect', async (req, res) => {
  const { username } = req.body;

  if (!username) {
    return res.status(400).json({ error: 'Se requiere el nombre de usuario' });
  }

  if (isConnecting) {
    return res.status(409).json({ error: 'Conexión ya en progreso' });
  }
  isConnecting = true;

  // Limpiar reconexión pendiente y conexión anterior
  currentUsername = null;
  if (reconnectTimer) { clearTimeout(reconnectTimer); reconnectTimer = null; }
  if (tiktokConnection) {
    tiktokConnection.removeAllListeners();
    try { tiktokConnection.disconnect(); } catch (e) {}
    tiktokConnection = null;
  }

  const cleanUsername = username.replace('@', '').trim();

  resetOverlayState();

  try {
    setupTikTokConnection(cleanUsername);
    const state = await tiktokConnection.connect();

    const baseCount = extractFollowerCount(state && state.roomInfo);
    if (baseCount > 0) {
      overlayState.baseFollowerCount = baseCount;
      broadcast({ type: 'follower-base', count: baseCount });
      log('info', 'connect', 'Base follower count extracted', { count: baseCount });
    }
    startFollowerRefresh();

    currentUsername = cleanUsername;
    reconnectAttempts = 0;

    broadcast({ type: 'connected', username: cleanUsername });
    res.json({ success: true, username: cleanUsername });

  } catch (err) {
    log('error', 'connect', 'TikTok connection failed', { error: err.message });
    tiktokConnection = null;
    res.status(500).json({
      error: err.message.includes('LIVE')
        ? `@${cleanUsername} no está en vivo ahora mismo`
        : err.message.includes('not found')
        ? `Usuario @${cleanUsername} no encontrado`
        : `No se pudo conectar: ${err.message}`
    });
  } finally {
    isConnecting = false;
  }
});

// Disconnect
app.post('/api/disconnect', (req, res) => {
  currentUsername = null;
  reconnectAttempts = 0;
  stopFollowerRefresh();
  if (reconnectTimer) { clearTimeout(reconnectTimer); reconnectTimer = null; }
  if (tiktokConnection) {
    tiktokConnection.removeAllListeners();
    likePendingTimers.clear();
    try { tiktokConnection.disconnect(); } catch (e) {}
    tiktokConnection = null;
  }
  broadcast({ type: 'disconnected' });
  res.json({ success: true });
});

// Text to Speech endpoint
app.post('/api/tts', async (req, res) => {
  const { text, voice = 'es' } = req.body;
  if (!text) return res.status(400).json({ error: 'Texto requerido' });
  if (isTTSRateLimited()) {
    return res.status(429).json({ error: 'Rate limit activo', retryAfter: config.TTS_RATE_WINDOW_MS });
  }
  const limitedText = sanitizeForTTS(text.substring(0, config.TTS_MAX_CHARS));
  log('info', 'tts', 'request', { voice, len: limitedText.length });

  // ── Google TTS (online, múltiples idiomas) ─────────────────
  try {
    const lang = voice.split('-')[0];
    const audioUrl = gTTS.getAudioUrl(limitedText, {
      lang: lang,
      slow: false,
      host: 'https://translate.google.com',
    });

    const req_tts = https.get(audioUrl, { headers: { 'User-Agent': 'Mozilla/5.0' } }, (audioRes) => {
      const contentType = audioRes.headers['content-type'] || '';
      const contentLen = parseInt(audioRes.headers['content-length'] || '0', 10);

      log('info', 'tts', 'Google response', { status: audioRes.statusCode, contentType, len: contentLen });

      if (audioRes.statusCode !== 200) {
        let errorBody = '';
        audioRes.on('data', chunk => { errorBody += chunk.toString().substring(0, 500); });
        audioRes.on('end', () => {
          log('error', 'tts', 'Google TTS HTTP error', { status: audioRes.statusCode, contentType, errorBody });
          res.status(500).json({ error: `Google TTS error: HTTP ${audioRes.statusCode}` });
        });
        return;
      }

      if (!contentType.includes('audio/mpeg') && !contentType.includes('audio')) {
        log('error', 'tts', 'Invalid content-type from Google', { contentType, len: contentLen });
        return res.status(500).json({ error: 'Invalid audio format from TTS service' });
      }

      if (contentLen < 1000) {
        log('warn', 'tts', 'Small audio response', { len: contentLen, contentType });
      }

      res.setHeader('Content-Type', 'audio/mpeg');
      res.setHeader('Cache-Control', 'no-cache');
      audioRes.pipe(res);
    });

    req_tts.setTimeout(15000, () => {
      req_tts.destroy();
      log('error', 'tts', 'Google TTS timeout (15s)', { voice, textLen: limitedText.length });
      if (!res.headersSent) {
        res.status(500).json({ error: 'TTS service timeout' });
      }
    });

    req_tts.on('error', err => {
      log('error', 'tts', 'Google TTS network error', { error: err.message, voice });
      if (!res.headersSent) {
        res.status(500).json({ error: err.message });
      }
    });

  } catch (err) {
    log('error', 'tts', 'Google TTS failed', { error: err.message });
    res.status(500).json({ error: err.message });
  }
});

// Translation endpoint
app.post('/api/translate', async (req, res) => {
  const { text, targetLang = 'es' } = req.body;
  if (!text) return res.status(400).json({ error: 'text required' });
  try {
    const { translate } = require('@vitalets/google-translate-api');
    const result = await translate(text.substring(0, 500), { to: targetLang });
    res.json({ translated: result.text, detectedLang: result.src || 'und' });
  } catch (err) {
    log('error', 'translate', 'Translation failed', { error: err.message });
    res.status(500).json({ error: err.message });
  }
});

// Edge TTS endpoint (Microsoft Neural voices)
app.post('/api/tts/edge', async (req, res) => {
  const { text, voice = 'es-ES-AlvaroNeural' } = req.body;
  if (!text) return res.status(400).json({ error: 'Texto requerido' });
  if (isTTSRateLimited()) {
    return res.status(429).json({ error: 'Rate limit activo', retryAfter: config.TTS_RATE_WINDOW_MS });
  }
  const limitedText = sanitizeForTTS(text.substring(0, config.TTS_MAX_CHARS));
  log('info', 'tts', 'edge request', { voice, len: limitedText.length });

  try {
    const tts = new MsEdgeTTS();
    await tts.setMetadata(voice, OUTPUT_FORMAT.AUDIO_24KHZ_48KBITRATE_MONO_MP3);
    const readable = tts.toStream(limitedText);
    res.setHeader('Content-Type', 'audio/mpeg');
    res.setHeader('Cache-Control', 'no-cache');
    readable.on('error', (err) => {
      log('error', 'tts', 'Edge TTS stream error', { error: err.message });
      if (!res.headersSent) res.status(500).json({ error: err.message });
      else res.end();
    });
    readable.pipe(res);
  } catch (err) {
    log('error', 'tts', 'Edge TTS failed', { error: err.message });
    if (!res.headersSent) res.status(500).json({ error: err.message });
  }
});

// Available voices endpoint
app.get('/api/voices', (req, res) => {
  const voices = [];

  // ── Edge TTS (Microsoft Neural) — Español ──────────────────
  const edgeVoicesEs = [
    { id: 'edge-es-ES-AlvaroNeural',  name: 'Álvaro — Edge TTS (España)',  flag: 'ES', engine: 'edge' },
    { id: 'edge-es-MX-JorgeNeural',   name: 'Jorge — Edge TTS (México)',   flag: 'MX', engine: 'edge' },
    { id: 'edge-es-MX-DaliaNeural',   name: 'Dalia — Edge TTS (México)',   flag: 'MX', engine: 'edge' },
    { id: 'edge-es-AR-ElenaNeural',   name: 'Elena — Edge TTS (Argentina)', flag: 'AR', engine: 'edge' },
  ];

  // ── Google TTS ──────────────────────────────────────────────
  const googleVoices = [
    // Español
    { id: 'es', name: 'Español (España) — Google', flag: 'ES' },
    { id: 'es-MX', name: 'Español (México) — Google', flag: 'MX' },
    { id: 'es-AR', name: 'Español (Argentina) — Google', flag: 'AR' },

    // Inglés
    { id: 'en', name: 'English (USA)', flag: 'US' },
    { id: 'en-GB', name: 'English (UK)', flag: 'GB' },

    // Portugués
    { id: 'pt', name: 'Português (Brasil)', flag: 'BR' },
    { id: 'pt-PT', name: 'Português (Portugal)', flag: 'PT' },

    // Francés
    { id: 'fr', name: 'Français', flag: 'FR' },

    // Alemán
    { id: 'de', name: 'Deutsch', flag: 'DE' },

    // Italiano
    { id: 'it', name: 'Italiano', flag: 'IT' },

    // Otros idiomas
    { id: 'ja', name: '日本語 (Japonés)', flag: 'JP' },
    { id: 'zh-CN', name: '中文 (Chino)', flag: 'CN' },
    { id: 'ru', name: 'Русский (Ruso)', flag: 'RU' },
    { id: 'ko', name: '한국어 (Coreano)', flag: 'KR' },
  ];

  voices.push(...edgeVoicesEs, ...googleVoices);
  res.json(voices);
});

// Health check
app.get('/api/status', (req, res) => {
  res.json({
    connected: tiktokConnection !== null,
    wsClients: clients.size,
    uptime: Math.floor(process.uptime()),
    memoryMB: Math.round(process.memoryUsage().heapUsed / 1024 / 1024),
    config,
    timestamp: new Date().toISOString()
  });
});

// Config dinámico
app.get('/api/config', (req, res) => res.json(config));

app.patch('/api/config', (req, res) => {
  const allowed = Object.keys(config);
  for (const [k, v] of Object.entries(req.body)) {
    if (allowed.includes(k) && typeof v === typeof config[k]) config[k] = v;
  }
  log('info', 'config', 'updated', config);
  res.json(config);
});

// Palabras bloqueadas
app.get('/api/blocked-words', (req, res) => res.json({ words: [...blockedWords] }));

app.get('/api/blocked-words/export', (req, res) => {
  try {
    if (!fs.existsSync(BLOCKED_WORDS_FILE)) return res.type('text/plain').send('');
    const content = fs.readFileSync(BLOCKED_WORDS_FILE, 'utf-8');
    res.type('text/plain').send(content);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/blocked-words/import', (req, res) => {
  const { content } = req.body;
  if (typeof content !== 'string') return res.status(400).json({ error: 'Se requiere content' });
  blockedWords.clear();
  const lines = content.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('- ') || trimmed.startsWith('* ')) {
      const word = trimmed.slice(2).toLowerCase().trim();
      if (word) blockedWords.add(word);
    }
  }
  saveBlockedWordsToFile();
  res.json({ words: [...blockedWords] });
});

app.post('/api/block-word', (req, res) => {
  const { word } = req.body;
  if (word && typeof word === 'string') blockedWords.add(word.toLowerCase().trim());
  saveBlockedWordsToFile();
  res.json({ words: [...blockedWords] });
});

app.delete('/api/block-word', (req, res) => {
  const { word } = req.body;
  if (word) blockedWords.delete(word.toLowerCase().trim());
  saveBlockedWordsToFile();
  res.json({ words: [...blockedWords] });
});

// Overlay stats for initial hydration
app.get('/api/overlay-stats', (req, res) => {
  const topLikers = [...overlayState.topLikers.values()]
    .sort((a, b) => b.totalLikes - a.totalLikes)
    .slice(0, 10);
  res.json({
    followCount: overlayState.followCount,
    baseFollowerCount: overlayState.baseFollowerCount,
    topLikers,
    sharers: overlayState.sharers.slice(-20),
    credits: {
      donors: overlayState.credits.donors.slice(-50),
      followers: overlayState.credits.followers.slice(-50),
      sharers: overlayState.credits.sharers.slice(-50),
    },
  });
});

// Gift file list for overlay name→filename mapping
app.get('/api/gifts-list', (req, res) => {
  const giftsDir = path.join(REAL_BASE, 'gifts');
  try {
    const files = fs.readdirSync(giftsDir).filter(f => f.endsWith('.png'));
    res.json(files);
  } catch (e) { res.json([]); }
});

// Upload custom background image
app.post('/api/upload-bg', upload.single('image'), (req, res) => {
  if (!req.file) return res.status(400).json({ error: 'No se recibió ninguna imagen' });
  const url = `/uploads/${req.file.filename}`;
  log('info', 'upload-bg', 'Background uploaded', { url, size: req.file.size });
  res.json({ url });
});

app.delete('/api/upload-bg', (req, res) => {
  const { filename } = req.body;
  if (!filename || typeof filename !== 'string') {
    return res.status(400).json({ error: 'Se requiere filename' });
  }
  const safeName = path.basename(filename);
  const filePath = path.join(UPLOADS_DIR, safeName);
  try {
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
      log('info', 'upload-bg', 'Background deleted', { filename: safeName });
      res.json({ success: true });
    } else {
      res.status(404).json({ error: 'Archivo no encontrado' });
    }
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// Test endpoints
app.post('/api/test/gift', (req, res) => {
  const giftsDir = path.join(REAL_BASE, 'gifts');
  try {
    const files = fs.readdirSync(giftsDir).filter(f => f.endsWith('.png'));
    if (files.length === 0) return res.status(500).json({ error: 'No hay imágenes de regalos' });
    const file = files[Math.floor(Math.random() * files.length)];
    const match = file.match(/^\d+_(.+)\.png$/i);
    const giftName = match ? match[1].replace(/_/g, ' ') : 'Regalo';
    const testUsers = ['TestUser', 'FanRandom', 'ViewerPro', 'TikToker', 'StreamerFan'];
    const user = testUsers[Math.floor(Math.random() * testUsers.length)] + Math.floor(Math.random() * 99);
    broadcast({
      type: 'gift',
      user,
      giftName,
      repeatCount: 1,
      timestamp: Date.now(),
      test: true,
      duration: 10000,
    });
    log('info', 'test', 'Test gift broadcasted', { user, giftName });
    res.json({ success: true, user, giftName });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

app.post('/api/test/follow', (req, res) => {
  const testUsers = ['TestUser', 'FanRandom', 'ViewerPro', 'TikToker', 'StreamerFan'];
  const user = testUsers[Math.floor(Math.random() * testUsers.length)] + Math.floor(Math.random() * 99);
  overlayState.credits.followers.push({ user, ts: Date.now() });
  broadcast({ type: 'follow', user, timestamp: Date.now() });
  overlayState.followCount += 1;
  log('info', 'test', 'Test follow broadcasted', { user });
  res.json({ success: true, user });
});

app.post('/api/test/share', (req, res) => {
  const testUsers = ['ShareKing', 'ViralFan', 'StreamShare', 'TikToker', 'TopViewer'];
  const user = testUsers[Math.floor(Math.random() * testUsers.length)] + Math.floor(Math.random() * 99);
  overlayState.sharers.push({ user, ts: Date.now() });
  overlayState.credits.sharers.push({ user, ts: Date.now() });
  broadcast({ type: 'share', user, timestamp: Date.now() });
  log('info', 'test', 'Test share broadcasted', { user });
  res.json({ success: true, user });
});

app.post('/api/test/likes', (req, res) => {
  const testUsers = ['LikeKing', 'FanTotal', 'TikTokLover', 'SuperViewer', 'HeartGiver', 'StreamFan', 'TopLiker', 'MegaFan'];
  const count = Math.floor(Math.random() * 6) + 5;
  for (let i = 0; i < count; i++) {
    const user = testUsers[i % testUsers.length] + Math.floor(Math.random() * 99);
    const likeCount = Math.floor(Math.random() * 490) + 10;
    broadcast({
      type: 'like',
      user,
      likeCount,
      timestamp: Date.now() + i,
    });
  }
  log('info', 'test', 'Test likes broadcasted', { count });
  res.json({ success: true, count });
});

// ── AUTH TOKENS & PLATFORM CONFIG ────────────────────────────────────────────
const authTokens = { twitch: null, twitchLogin: null };
const platformConfig = { twitchClientId: '' };

// ── MULTI-PLATFORM CHAT ───────────────────────────────────────────────────────
const platformConnections = { twitch: null, youtube: null };
let obsWs = null;

async function connectTwitch(channel, token = null) {
  const tmi = require('tmi.js');
  if (platformConnections.twitch) {
    try { await platformConnections.twitch.disconnect(); } catch (e) {}
    platformConnections.twitch = null;
  }
  const clientOpts = { channels: [channel] };
  if (token && authTokens.twitchLogin) {
    clientOpts.identity = { username: authTokens.twitchLogin, password: `oauth:${token}` };
  }
  const client = new tmi.Client(clientOpts);

  client.on('message', (_ch, tags, message, self) => {
    if (self || !message.trim()) return;
    if (isSpam(message.trim())) return;
    // Parse Twitch emotes for visual rendering
    const emotes = {};
    if (tags.emotes) {
      for (const [emoteId, positions] of Object.entries(tags.emotes)) {
        const range = Array.isArray(positions) ? positions[0] : positions.split('/')[0];
        const [start, end] = range.split('-').map(Number);
        const name = message.substring(start, end + 1);
        if (name) emotes[name] = { url: `https://static-cdn.jtvnw.net/emoticons/v2/${emoteId}/default/dark/1.0` };
      }
    }
    broadcast({
      type: 'chat',
      platform: 'twitch',
      user: cleanName(tags['display-name'] || tags.username || 'Anónimo'),
      comment: sanitizeForTTS(message.trim()),
      emotes: Object.keys(emotes).length > 0 ? emotes : undefined,
      timestamp: Date.now(),
    });
  });

  client.on('disconnected', () => broadcast({ type: 'platform-disconnected', platform: 'twitch' }));

  await client.connect();
  platformConnections.twitch = client;
  broadcast({ type: 'platform-connected', platform: 'twitch' });
  log('info', 'twitch', 'Twitch conectado', { channel });
}

async function connectYoutube(channelOrId) {
  const { LiveChat } = require('youtube-chat');
  if (platformConnections.youtube) {
    try { platformConnections.youtube.stop(); } catch (e) {}
    platformConnections.youtube = null;
  }
  const opts = channelOrId.startsWith('@') ? { handle: channelOrId } : { liveId: channelOrId };
  const liveChat = new LiveChat(opts);

  liveChat.on('chat', (item) => {
    // Parse YouTube emoji/sticker runs for visual rendering
    const emotes = {};
    const displayParts = [];
    for (const part of (item.message || [])) {
      if (part.text) {
        displayParts.push(part.text);
      } else if (part.emoji) {
        const rawName = part.emoji.emojiId || part.emoji.shortcuts?.[0] || '';
        const safeName = rawName.replace(/[^a-zA-Z0-9_\-]/g, '_') || 'emoji';
        const thumbs = part.emoji.image?.thumbnails || [];
        const url = thumbs[thumbs.length - 1]?.url || '';
        displayParts.push(`:${safeName}:`);
        if (url) emotes[safeName] = { url };
      }
    }
    const displayText = displayParts.join('').trim();
    const ttsText = displayText.replace(/:[\w\-]+:/g, '').trim();
    if (!displayText || isSpam(ttsText || displayText)) return;
    broadcast({
      type: 'chat',
      platform: 'youtube',
      user: cleanName(item.author?.name || 'Anónimo'),
      comment: sanitizeForTTS(displayText),
      ttsComment: ttsText ? sanitizeForTTS(ttsText) : undefined,
      emotes: Object.keys(emotes).length > 0 ? emotes : undefined,
      timestamp: Date.now(),
    });
  });

  liveChat.on('error', (err) => {
    log('warn', 'youtube', 'YouTube chat error', { error: String(err) });
    broadcast({ type: 'platform-disconnected', platform: 'youtube' });
  });

  const ok = await liveChat.start();
  if (!ok) throw new Error('No se pudo iniciar el chat de YouTube (¿el canal está en vivo?)');
  platformConnections.youtube = liveChat;
  broadcast({ type: 'platform-connected', platform: 'youtube' });
  log('info', 'youtube', 'YouTube conectado', { channelOrId });
}

// ── PLATFORM ENDPOINTS ────────────────────────────────────────────────────────
app.get('/api/platforms/status', (_req, res) => {
  res.json({
    twitch: !!platformConnections.twitch,
    youtube: !!platformConnections.youtube,
  });
});

app.post('/api/platforms/connect', async (req, res) => {
  const { platform, channel, token } = req.body;
  if (!platform || !channel) return res.status(400).json({ error: 'Se requiere platform y channel' });

  try {
    if (platform === 'twitch') {
      // Accept full URLs: https://www.twitch.tv/channel → channel
      const twitchChannel = channel.replace(/^https?:\/\/(www\.)?twitch\.tv\//i, '').replace('#', '').trim();
      await connectTwitch(twitchChannel, token || null);
    } else if (platform === 'youtube') {
      // Accept full URLs: https://www.youtube.com/@handle → @handle
      // https://www.youtube.com/watch?v=ID or youtu.be/ID → ID
      let ytInput = channel.trim();
      const ytWatchMatch = ytInput.match(/[?&]v=([^&]+)/);
      const ytShortMatch = ytInput.match(/youtu\.be\/([^?]+)/);
      const ytHandleMatch = ytInput.match(/youtube\.com\/@?([\w.-]+)/i);
      if (ytWatchMatch) ytInput = ytWatchMatch[1];
      else if (ytShortMatch) ytInput = ytShortMatch[1];
      else if (ytHandleMatch) ytInput = '@' + ytHandleMatch[1];
      await connectYoutube(ytInput);
    } else return res.status(400).json({ error: 'Plataforma no soportada' });
    res.json({ success: true });
  } catch (err) {
    log('error', platform, 'Error al conectar', { error: err.message });
    res.status(500).json({ error: err.message });
  }
});

app.post('/api/platforms/disconnect', async (req, res) => {
  const { platform } = req.body;
  try {
    if (platform === 'twitch' && platformConnections.twitch) {
      await platformConnections.twitch.disconnect();
      platformConnections.twitch = null;
      broadcast({ type: 'platform-disconnected', platform: 'twitch' });
    } else if (platform === 'youtube' && platformConnections.youtube) {
      platformConnections.youtube.stop();
      platformConnections.youtube = null;
      broadcast({ type: 'platform-disconnected', platform: 'youtube' });
    }
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── OBS WEBSOCKET ─────────────────────────────────────────────────────────────
app.post('/api/obs/connect', (req, res) => {
  const { port = 4455, password = '' } = req.body || {};

  if (obsWs) {
    try { obsWs.close(); } catch (_) {}
    obsWs = null;
  }

  let settled = false;
  const settle = (fn) => { if (!settled) { settled = true; fn(); } };
  let ws;

  try {
    ws = new WebSocket(`ws://127.0.0.1:${port}`);
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }

  const timeoutId = setTimeout(() => {
    settle(() => {
      try { ws.close(); } catch (_) {}
      res.status(500).json({ error: 'Timeout al conectar OBS (5s)' });
    });
  }, 5000);

  ws.on('message', (raw) => {
    try {
      const msg = JSON.parse(raw.toString());
      if (msg.op === 0) {
        // Hello — send Identify (op 1)
        const d = { rpcVersion: 1 };
        const authChallenge = msg.d && msg.d.authentication;
        if (authChallenge && password) {
          const secret = crypto.createHash('sha256')
            .update(password + authChallenge.salt).digest('base64');
          d.authentication = crypto.createHash('sha256')
            .update(secret + authChallenge.challenge).digest('base64');
        }
        d.eventSubscriptions = 64; // OutputEvents bitmask — includes StreamStateChanged
        ws.send(JSON.stringify({ op: 1, d }));
      } else if (msg.op === 2) {
        // Identified — connection established
        clearTimeout(timeoutId);
        obsWs = ws;
        broadcast({ type: 'obs-connected' });
        settle(() => res.json({ success: true }));
      } else if (msg.op === 5) {
        // Event — handle StreamStateChanged to auto-start/stop stream timer
        const { eventType, eventData } = msg.d || {};
        if (eventType === 'StreamStateChanged') {
          if (eventData && eventData.outputState === 'OBS_WEBSOCKET_OUTPUT_STARTED') {
            broadcast({ type: 'obs-stream-started' });
          } else if (eventData && eventData.outputState === 'OBS_WEBSOCKET_OUTPUT_STOPPED') {
            broadcast({ type: 'obs-stream-stopped' });
          }
        }
      }
    } catch (_) {}
  });

  ws.on('error', (err) => {
    clearTimeout(timeoutId);
    settle(() => res.status(500).json({ error: err.message }));
  });

  ws.on('close', () => {
    clearTimeout(timeoutId);
    if (obsWs === ws) {
      obsWs = null;
      broadcast({ type: 'obs-disconnected' });
    }
    settle(() => res.status(500).json({ error: 'OBS cerró la conexión' }));
  });
});

app.post('/api/obs/disconnect', (_req, res) => {
  if (obsWs) {
    try { obsWs.close(); } catch (_) {}
    obsWs = null;
    broadcast({ type: 'obs-disconnected' });
  }
  res.json({ success: true });
});

app.post('/api/obs/save-replay', (_req, res) => {
  if (!obsWs || obsWs.readyState !== WebSocket.OPEN) {
    return res.status(400).json({ error: 'OBS no conectado' });
  }
  try {
    obsWs.send(JSON.stringify({
      op: 6,
      d: { requestType: 'SaveReplayBuffer', requestId: `replay-${Date.now()}` }
    }));
    res.json({ success: true });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.get('/api/platform-config', (_req, res) => res.json(platformConfig));

app.patch('/api/platform-config', (req, res) => {
  const allowed = Object.keys(platformConfig);
  for (const [k, v] of Object.entries(req.body)) {
    if (allowed.includes(k) && typeof v === 'string') platformConfig[k] = v;
  }
  res.json(platformConfig);
});

app.get('/auth/twitch/callback', (_req, res) => {
  res.send(`<!DOCTYPE html><html><head><title>Twitch Auth</title></head><body>
    <p style="font-family:sans-serif;padding:20px">Autenticando con Twitch...</p>
    <script>
      const hash = new URLSearchParams(location.hash.slice(1));
      const token = hash.get('access_token');
      if (token) {
        fetch('/auth/twitch/token', {
          method: 'POST',
          headers: {'Content-Type':'application/json'},
          body: JSON.stringify({ token })
        }).then(() => { document.body.innerHTML = '<p style="font-family:sans-serif;padding:20px;color:green">✓ Twitch conectado. Puedes cerrar esta ventana.</p>'; });
      } else {
        document.body.innerHTML = '<p style="font-family:sans-serif;padding:20px;color:red">Error: no se recibió token. Intenta de nuevo.</p>';
      }
    <\/script>
  </body></html>`);
});

app.post('/auth/twitch/token', async (req, res) => {
  const { token } = req.body;
  if (!token) return res.status(400).json({ error: 'Token requerido' });
  if (!platformConfig.twitchClientId) {
    return res.status(400).json({ error: 'Cliente ID de Twitch no configurado. Ve a Configuración > Plataformas.' });
  }
  authTokens.twitch = token;
  try {
    const { fetch: nodeFetch } = require('undici');
    const r = await nodeFetch('https://api.twitch.tv/helix/users', {
      headers: { 'Authorization': `Bearer ${token}`, 'Client-Id': platformConfig.twitchClientId },
    });
    if (!r.ok) {
      authTokens.twitchLogin = null;
      return res.status(401).json({ error: 'Token inválido o Client ID incorrecto' });
    }
    const d = await r.json();
    authTokens.twitchLogin = d.data?.[0]?.login || null;
  } catch (e) {
    authTokens.twitchLogin = null;
    return res.status(502).json({ error: 'Error contactando Twitch', detail: e.message });
  }
  broadcast({ type: 'twitch-auth-ready', login: authTokens.twitchLogin });
  log('info', 'twitch-oauth', 'Token recibido', { login: authTokens.twitchLogin });
  res.json({ success: true, login: authTokens.twitchLogin });
});

// Cargar palabras bloqueadas al iniciar
loadBlockedWordsFromFile();

const PORT = process.env.PORT || 3000;

server.on('error', (err) => {
  if (err.code === 'EADDRINUSE') {
    require('child_process').exec(`start http://localhost:${PORT}`);
    process.exit(0);
  }
});

server.listen(PORT, () => {
  console.log(`\nTikTok Live TTS corriendo en http://localhost:${PORT}\n`);
  if (IS_PKG) {
    require('child_process').exec(`start http://localhost:${PORT}`);
    const { initTray } = require('./tray');
    initTray(PORT);
  }
  // In Electron mode, main.js opens the BrowserWindow after detecting this port is up
});
